name: Node.JS CI

on:
  pull_request:
  push:
    branches:
      - main
    paths:
      - "**.ts"
      - "**.js"
      - "**.svelte"
      - "*/package-lock.json"
      - "*/package.json"

jobs:
  build:
    name: ${{ matrix.os }} with Node.JS v${{ matrix.version }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest
        version:
          - 12.x
          - 14.x

    steps:
      - name: Install Node.JS v${{ matrix.version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.version }}

      - uses: actions/checkout@v2

      - name: Log versions
        run: |
          node -v
          npm -v
      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Build source
        run: npm run build --if-present
